# Generated by Django 4.1.3 on 2023-10-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OJInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('payee_name', models.CharField(max_length=100)),
                ('payee_address', models.TextField(default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('settlement', models.CharField(default='unsettled', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaylabsPaymentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.CharField(max_length=64)),
                ('errCode', models.CharField(max_length=32)),
                ('errCodeDes', models.CharField(blank=True, max_length=128, null=True)),
                ('merchantId', models.CharField(max_length=20)),
                ('storeId', models.CharField(blank=True, max_length=30, null=True)),
                ('paymentType', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchantTradeNo', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('platformTradeNo', models.CharField(blank=True, max_length=32, null=True)),
                ('successTime', models.DateTimeField(blank=True, null=True)),
                ('expiredTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('productName', models.CharField(max_length=100)),
                ('productInfo', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=12)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement', models.IntegerField(default=1)),
                ('transaction_fee', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OJInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_type', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_detail', models.JSONField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.ojinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='ojinvoice',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentoption'),
        ),
    ]
