# Generated by Django 4.1.3 on 2023-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ojinvoice_transaction_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
