# Generated by Django 4.1.3 on 2023-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_ojinvoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojinvoice',
            name='transaction_ref_id',
            field=models.CharField(max_length=200),
        ),
    ]
