# Generated by Django 4.1.3 on 2023-10-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_ojinvoice_transaction_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=100)),
                ('requests_header', models.JSONField(blank=True, null=True)),
                ('requests_body', models.JSONField(blank=True, null=True)),
                ('response_header', models.JSONField(blank=True, null=True)),
                ('resonse_body', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaylabsPaymentResponse',
        ),
    ]
